### ISSUE TITLE
Record progress of multiple files

### ISSUE THREAD

**Issue by callumalpass** [RyotaUshio/obsidian-view-sync#1]
Hi, 

I've found the plugins that you've been working on really useful--in particular pdf++--and want to thank you very much for that. This new plugin seems like a very useful addition. 

I was wondering whether you would consider storing the reading progress of each file that is viewed, rather than storing the progress of only the current file viewed? 

Currently, I rely on Omnivore for reading longer pdfs from beginning to end, because Obsidian tends to lose track of my reading progress when I'm reading across several sessions and/or devices. With this plugin recording the reading progress of each pdf, Obsidian may be able to replace this functionality of Omnivore. 

I was wondering, also, whether bi-directional sync would be possible if at each recording of the page number, there was a timestamp? And then the most recent page number would be opened. 

Would either of these features be likely to be implemented in this plugin?

Thanks again!!

**Comment by RyotaUshio** [comment]
Thanks!

> I was wondering whether you would consider storing the reading progress of each file that is viewed, rather than storing the progress of only the current file viewed?

That would be a nice feature to have. It would be better handled by PDF++ rather than this plugin, though.
What I have in mind for now is:

1. Each device records the latest progress (page, zoom level etc) and a timestamp in its own dedicated file like `pdf-progress-macbook.json`.
2. When opening a PDF file, PDF++ looks up the latest progress in the file, then sets the page number and so on accordingly.

This way, we will be able to record progress in each device. In addition, we could add an option like "share progress across devices" and specify which file to read another device's progress from (e.g. `pdf-progress-ipad.json`).

If this option is enabled, PDF++ compares the timestamps from all the devices and follows the latest one.

> I was wondering, also, whether bi-directional sync would be possible if at each recording of the page number, there was a timestamp? And then the most recent page number would be opened.

It's something this plugin might be able to handle. I will consider the possibilities.

**Comment by callumalpass** [comment]
That sounds like a great solution, thanks! The speed of development of this plugins is amazing and much appreciated!

**Comment by RyotaUshio** [comment]
I've just released [0.2.0](https://github.com/RyotaUshio/obsidian-view-sync/releases/tag/0.2.0), in which a timestamp will be included in the view state file. You can choose to sync view states only if the followed device has a newer state than the current device.

I haven't been able to do enough tests on this version so if you encounter any issues, please let me know.
